import AppKit
import ApplicationServices
import CoreGraphics
import Foundation

enum SyntheticEventTag {
    // ASCII "WHISPRGO". The global hotkey tap lets these events pass through
    // without interpreting WhisprGo's own Cmd-V as a configured shortcut.
    static let pasteCommand: Int64 = 0x5748_4953_5052_474F
}

@MainActor
enum TextInjector {
    private static let webAreaRole = "AXWebArea"
    private static let pasteEventDelay = Duration.milliseconds(5)
    private static let pasteboardRestoreDelay = Duration.seconds(1)
    static let pasteSessionType = NSPasteboard.PasteboardType(
        "com.whisprgo.app.PasteSession"
    )
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    private static let transientType = NSPasteboard.PasteboardType(
        "org.nspasteboard.TransientType"
    )
    private static let autoGeneratedType = NSPasteboard.PasteboardType(
        "org.nspasteboard.AutoGeneratedType"
    )
    private static var pendingPasteboardRestore: PendingPasteboardRestore?
    private static var pasteboardRestoreTask: Task<Void, Never>?
    private static let richEditorBundleIDs: Set<String> = [
        "com.apple.mail",
        "com.microsoft.outlook",
        "com.mimestream.mimestream",
        "com.readdle.smartemail-macos",
        "io.canarymail.mac",
    ]

    struct Target {
        let element: AXUIElement
        let processIdentifier: pid_t
        let prefersPaste: Bool
    }

    enum Result: Equatable {
        case inserted
        case ignored
        case failed(String)

        var errorMessage: String? {
            guard case let .failed(message) = self else { return nil }
            return message
        }
    }

    /// Capturing the destination before recording prevents transient call and
    /// screen-sharing controls from stealing the insertion target while the
    /// transcript is being produced.
    static func captureTarget() -> Target? {
        guard AXIsProcessTrusted() else { return nil }

        let system = AXUIElementCreateSystemWide()
        var focusedValue: CFTypeRef?
        let lookup = AXUIElementCopyAttributeValue(
            system,
            kAXFocusedUIElementAttribute as CFString,
            &focusedValue
        )
        guard lookup == .success, let focusedValue else { return nil }

        let focused = focusedValue as! AXUIElement
        var processIdentifier: pid_t = 0
        guard AXUIElementGetPid(focused, &processIdentifier) == .success else { return nil }
        let bundleIdentifier = NSRunningApplication(
            processIdentifier: processIdentifier
        )?.bundleIdentifier?.lowercased()
        let role = stringAttribute(focused, kAXRoleAttribute)
        let isKnownRichEditor = role == kAXTextAreaRole
            && bundleIdentifier.map(richEditorBundleIDs.contains) == true
        return Target(
            element: focused,
            processIdentifier: processIdentifier,
            prefersPaste: isKnownRichEditor || isInsideWebContent(focused)
        )
    }

    static func inject(_ text: String, into capturedTarget: Target? = nil) async -> Result {
        guard !text.isEmpty else { return .ignored }
        guard AXIsProcessTrusted() else {
            return .failed("Text could not be inserted. Allow WhisprGo in Accessibility settings.")
        }

        let target = capturedTarget ?? captureTarget()
        if let target, !target.prefersPaste, insertDirectly(text, into: target.element) {
            return .inserted
        }

        return await paste(text, into: target)
    }

    private static func paste(_ text: String, into target: Target?) async -> Result {
        let pasteboard = NSPasteboard.general
        restorePendingPasteboardIfOwned(on: pasteboard)
        let snapshot = PasteboardSnapshot(pasteboard: pasteboard)
        let sessionID = UUID().uuidString
        let pasteboardItem = NSPasteboardItem()
        pasteboardItem.setString(text, forType: .string)
        pasteboardItem.setString(sessionID, forType: pasteSessionType)
        pasteboardItem.setData(Data(), forType: transientType)
        pasteboardItem.setData(Data(), forType: autoGeneratedType)
        if let bundleIdentifier = Bundle.main.bundleIdentifier {
            pasteboardItem.setString(bundleIdentifier, forType: sourceType)
        }

        pasteboard.clearContents()
        guard pasteboard.writeObjects([pasteboardItem]),
              pasteboard.string(forType: .string) == text
        else {
            snapshot.restore(on: pasteboard)
            return .failed("Text could not be copied for automatic insertion.")
        }
        let ownedChangeCount = pasteboard.changeCount

        if let target,
           NSWorkspace.shared.frontmostApplication?.processIdentifier != target.processIdentifier {
            guard let application = NSRunningApplication(
                processIdentifier: target.processIdentifier
            ), application.activate() else {
                snapshot.restore(on: pasteboard, ifChangeCountIs: ownedChangeCount)
                return .failed("The app you were dictating into is no longer available.")
            }

            // Activation is asynchronous. This is only paid on the uncommon
            // fallback path where direct Accessibility insertion was rejected.
            try? await Task.sleep(for: .milliseconds(70))
        }

        if let target {
            _ = AXUIElementSetAttributeValue(
                target.element,
                kAXFocusedAttribute as CFString,
                kCFBooleanTrue
            )
            // WebKit and Chromium commit focus asynchronously after their app
            // or editor is reactivated.
            try? await Task.sleep(for: .milliseconds(16))
        }

        guard await postPasteCommand() else {
            snapshot.restore(on: pasteboard, ifChangeCountIs: ownedChangeCount)
            return .failed("Text could not be inserted. Check Accessibility permission and try again.")
        }

        // Accessibility values in Chromium, WebKit, and rich editors can lag or
        // omit successful edits. Treat posting the paste command as delivery
        // instead of producing a false error from an unreliable AX read-back.
        // The one-second ownership window covers editors that consume Cmd-V
        // asynchronously and does not extend the latency-sensitive path.
        schedulePasteboardRestore(
            snapshot,
            on: pasteboard,
            expectedChangeCount: ownedChangeCount,
            text: text,
            sessionID: sessionID
        )
        return .inserted
    }

    private static func restorePendingPasteboardIfOwned(on pasteboard: NSPasteboard) {
        pasteboardRestoreTask?.cancel()
        pasteboardRestoreTask = nil
        guard let pendingPasteboardRestore else { return }
        Self.pendingPasteboardRestore = nil
        guard pasteboardIsOwned(
            pasteboard,
            expectedChangeCount: pendingPasteboardRestore.expectedChangeCount,
            text: pendingPasteboardRestore.text,
            sessionID: pendingPasteboardRestore.sessionID
        ) else { return }
        pendingPasteboardRestore.snapshot.restore(on: pasteboard)
    }

    private static func schedulePasteboardRestore(
        _ snapshot: PasteboardSnapshot,
        on pasteboard: NSPasteboard,
        expectedChangeCount: Int,
        text: String,
        sessionID: String
    ) {
        pendingPasteboardRestore = PendingPasteboardRestore(
            snapshot: snapshot,
            expectedChangeCount: expectedChangeCount,
            text: text,
            sessionID: sessionID
        )
        pasteboardRestoreTask = Task { @MainActor in
            do {
                try await Task.sleep(for: pasteboardRestoreDelay)
            } catch {
                return
            }
            guard let pendingPasteboardRestore,
                  pendingPasteboardRestore.sessionID == sessionID
            else { return }
            Self.pendingPasteboardRestore = nil
            pasteboardRestoreTask = nil
            guard pasteboardIsOwned(
                pasteboard,
                expectedChangeCount: expectedChangeCount,
                text: text,
                sessionID: sessionID
            ) else { return }
            snapshot.restore(on: pasteboard)
        }
    }

    static func pasteboardIsOwned(
        _ pasteboard: NSPasteboard,
        expectedChangeCount: Int,
        text: String,
        sessionID: String
    ) -> Bool {
        if pasteboard.changeCount == expectedChangeCount { return true }
        guard pasteboard.string(forType: .string) == text else { return false }
        let currentSessionID = pasteboard.string(forType: pasteSessionType)
        return currentSessionID == nil || currentSessionID == sessionID
    }

    private static func insertDirectly(_ text: String, into element: AXUIElement) -> Bool {
        let valueBefore = stringAttribute(element, kAXValueAttribute)
        let selectedRange = rangeAttribute(element, kAXSelectedTextRangeAttribute)
        guard AXUIElementSetAttributeValue(
            element,
            kAXSelectedTextAttribute as CFString,
            text as CFString
        ) == .success else { return false }

        guard let valueBefore else {
            // Native controls occasionally expose a writable selection without
            // exposing their full value. Web controls never take this branch.
            return true
        }
        guard let valueAfter = stringAttribute(element, kAXValueAttribute) else {
            return false
        }
        if let selectedRange,
           let expected = replacing(valueBefore, range: selectedRange, with: text) {
            return valueAfter == expected || valueAfter != valueBefore
        }
        return valueAfter != valueBefore
    }

    private static func isInsideWebContent(_ element: AXUIElement) -> Bool {
        var current: AXUIElement? = element
        for _ in 0..<10 {
            guard let candidate = current else { break }
            if stringAttribute(candidate, kAXRoleAttribute) == webAreaRole {
                return true
            }
            current = elementAttribute(candidate, kAXParentAttribute)
        }
        return false
    }

    static func replacing(
        _ value: String,
        range: CFRange,
        with replacement: String
    ) -> String? {
        let source = value as NSString
        guard range.location >= 0,
              range.length >= 0,
              range.location <= source.length,
              range.location + range.length <= source.length
        else { return nil }
        return source.replacingCharacters(
            in: NSRange(location: range.location, length: range.length),
            with: replacement
        )
    }

    private static func stringAttribute(
        _ element: AXUIElement,
        _ attribute: String
    ) -> String? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(
            element,
            attribute as CFString,
            &value
        ) == .success, let value else { return nil }
        if let string = value as? String { return string }
        return (value as? NSAttributedString)?.string
    }

    private static func rangeAttribute(
        _ element: AXUIElement,
        _ attribute: String
    ) -> CFRange? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(
            element,
            attribute as CFString,
            &value
        ) == .success,
              let value,
              CFGetTypeID(value) == AXValueGetTypeID()
        else { return nil }
        var range = CFRange()
        guard AXValueGetValue(value as! AXValue, .cfRange, &range) else { return nil }
        return range
    }

    private static func elementAttribute(
        _ element: AXUIElement,
        _ attribute: String
    ) -> AXUIElement? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(
            element,
            attribute as CFString,
            &value
        ) == .success,
              let value,
              CFGetTypeID(value) == AXUIElementGetTypeID()
        else { return nil }
        return (value as! AXUIElement)
    }

    private static func postPasteCommand() async -> Bool {
        guard let source = CGEventSource(stateID: .privateState),
              let commandDown = CGEvent(
                  keyboardEventSource: source,
                  virtualKey: 55,
                  keyDown: true
              ),
              let keyDown = CGEvent(
                  keyboardEventSource: source,
                  virtualKey: 9,
                  keyDown: true
              ),
              let keyUp = CGEvent(
                  keyboardEventSource: source,
                  virtualKey: 9,
                  keyDown: false
              ),
              let commandUp = CGEvent(
                  keyboardEventSource: source,
                  virtualKey: 55,
                  keyDown: false
              ) else {
            return false
        }

        commandDown.flags = .maskCommand
        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand
        for event in [commandDown, keyDown, keyUp, commandUp] {
            event.setIntegerValueField(
                .eventSourceUserData,
                value: SyntheticEventTag.pasteCommand
            )
        }
        commandDown.post(tap: .cghidEventTap)
        try? await Task.sleep(for: pasteEventDelay)
        keyDown.post(tap: .cghidEventTap)
        try? await Task.sleep(for: pasteEventDelay)
        keyUp.post(tap: .cghidEventTap)
        try? await Task.sleep(for: pasteEventDelay)
        commandUp.post(tap: .cghidEventTap)
        return true
    }

    private struct PendingPasteboardRestore {
        let snapshot: PasteboardSnapshot
        let expectedChangeCount: Int
        let text: String
        let sessionID: String
    }

    struct PasteboardSnapshot {
        struct Item {
            struct Representation {
                let type: NSPasteboard.PasteboardType
                let data: Data
            }

            let representations: [Representation]
        }

        let items: [Item]

        init(pasteboard: NSPasteboard) {
            items = (pasteboard.pasteboardItems ?? []).compactMap { pasteboardItem in
                let representations = pasteboardItem.types.compactMap { type -> Item.Representation? in
                    guard let data = pasteboardItem.data(forType: type) else { return nil }
                    return Item.Representation(type: type, data: data)
                }
                return representations.isEmpty ? nil : Item(representations: representations)
            }
        }

        @discardableResult
        func restore(
            on pasteboard: NSPasteboard,
            ifChangeCountIs expectedChangeCount: Int? = nil
        ) -> Bool {
            if let expectedChangeCount, pasteboard.changeCount != expectedChangeCount {
                return false
            }

            pasteboard.clearContents()
            guard !items.isEmpty else { return true }

            let restoredItems = items.map { item -> NSPasteboardItem in
                let restoredItem = NSPasteboardItem()
                for representation in item.representations {
                    restoredItem.setData(representation.data, forType: representation.type)
                }
                return restoredItem
            }
            return pasteboard.writeObjects(restoredItems)
        }
    }
}
